/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FeeStructure = IDL.Record({
  'transport' : IDL.Nat,
  'tuition' : IDL.Nat,
  'examFees' : IDL.Nat,
});
export const ClassInfo = IDL.Record({
  'subjects' : IDL.Vec(IDL.Text),
  'section' : IDL.Text,
  'feeStructure' : FeeStructure,
  'className' : IDL.Text,
});
export const EmployeeRole = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'supportStaff' : IDL.Null,
});
export const Employee = IDL.Record({
  'active' : IDL.Bool,
  'salary' : IDL.Nat,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'role' : EmployeeRole,
  'empId' : IDL.Text,
  'department' : IDL.Text,
});
export const Time = IDL.Int;
export const Exam = IDL.Record({
  'date' : Time,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'examId' : IDL.Text,
  'className' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Notice = IDL.Record({
  'title' : IDL.Text,
  'postedBy' : IDL.Text,
  'content' : IDL.Text,
  'postedDate' : Time,
  'noticeId' : IDL.Text,
  'attachment' : IDL.Opt(ExternalBlob),
});
export const Student = IDL.Record({
  'contact' : IDL.Text,
  'admissionDate' : Time,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'admissionNumber' : IDL.Text,
  'photo' : ExternalBlob,
  'className' : IDL.Text,
  'parentName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Attendance = IDL.Record({
  'present' : IDL.Bool,
  'date' : Time,
  'section' : IDL.Text,
  'studentAdmissionNumber' : IDL.Text,
  'className' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalEmployees' : IDL.Nat,
  'monthlyFeesCollected' : IDL.Nat,
  'totalStudents' : IDL.Nat,
  'pendingDues' : IDL.Nat,
});
export const PaymentMode = IDL.Variant({
  'cash' : IDL.Null,
  'cheque' : IDL.Null,
  'online' : IDL.Null,
});
export const FeePayment = IDL.Record({
  'fine' : IDL.Opt(IDL.Nat),
  'studentAdmissionNumber' : IDL.Text,
  'paymentDate' : Time,
  'discount' : IDL.Opt(IDL.Nat),
  'paymentMode' : PaymentMode,
  'amount' : IDL.Nat,
  'receiptNumber' : IDL.Text,
});
export const StudentMark = IDL.Record({
  'marks' : IDL.Nat,
  'subject' : IDL.Text,
  'studentAdmissionNumber' : IDL.Text,
  'grade' : IDL.Text,
  'examId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClass' : IDL.Func([ClassInfo], [], []),
  'addEmployee' : IDL.Func([Employee], [], []),
  'addExam' : IDL.Func([Exam], [], []),
  'addNotice' : IDL.Func([Notice], [], []),
  'addStudent' : IDL.Func([Student], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteClass' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [], []),
  'deleteExam' : IDL.Func([IDL.Text], [], []),
  'deleteNotice' : IDL.Func([IDL.Text], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'findAdminEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'findEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
  'findStudentByAdminNo' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'findSupportStaffEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'findTeacherEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllClasses' : IDL.Func([], [IDL.Vec(ClassInfo)], ['query']),
  'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getAttendance' : IDL.Func(
      [Time, IDL.Text, IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClass' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(ClassInfo)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getExam' : IDL.Func([IDL.Text], [IDL.Opt(Exam)], ['query']),
  'getFeeLedger' : IDL.Func([IDL.Text], [IDL.Vec(FeePayment)], ['query']),
  'getFeePayment' : IDL.Func([IDL.Text], [IDL.Opt(FeePayment)], ['query']),
  'getNotice' : IDL.Func([IDL.Text], [IDL.Opt(Notice)], ['query']),
  'getOutstandingBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getReportCard' : IDL.Func([IDL.Text], [IDL.Vec(StudentMark)], ['query']),
  'getStudentAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getStudentMarks' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(StudentMark)],
      ['query'],
    ),
  'getStudentsByClass' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([Attendance], [], []),
  'recordFeePayment' : IDL.Func([FeePayment], [], []),
  'recordMarks' : IDL.Func([StudentMark], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchStudentsByName' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'updateClass' : IDL.Func([IDL.Text, IDL.Text, ClassInfo], [], []),
  'updateEmployee' : IDL.Func([IDL.Text, Employee], [], []),
  'updateExam' : IDL.Func([IDL.Text, Exam], [], []),
  'updateNotice' : IDL.Func([IDL.Text, Notice], [], []),
  'updateStudent' : IDL.Func([IDL.Text, Student], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FeeStructure = IDL.Record({
    'transport' : IDL.Nat,
    'tuition' : IDL.Nat,
    'examFees' : IDL.Nat,
  });
  const ClassInfo = IDL.Record({
    'subjects' : IDL.Vec(IDL.Text),
    'section' : IDL.Text,
    'feeStructure' : FeeStructure,
    'className' : IDL.Text,
  });
  const EmployeeRole = IDL.Variant({
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'supportStaff' : IDL.Null,
  });
  const Employee = IDL.Record({
    'active' : IDL.Bool,
    'salary' : IDL.Nat,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'role' : EmployeeRole,
    'empId' : IDL.Text,
    'department' : IDL.Text,
  });
  const Time = IDL.Int;
  const Exam = IDL.Record({
    'date' : Time,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'examId' : IDL.Text,
    'className' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Notice = IDL.Record({
    'title' : IDL.Text,
    'postedBy' : IDL.Text,
    'content' : IDL.Text,
    'postedDate' : Time,
    'noticeId' : IDL.Text,
    'attachment' : IDL.Opt(ExternalBlob),
  });
  const Student = IDL.Record({
    'contact' : IDL.Text,
    'admissionDate' : Time,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'admissionNumber' : IDL.Text,
    'photo' : ExternalBlob,
    'className' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Attendance = IDL.Record({
    'present' : IDL.Bool,
    'date' : Time,
    'section' : IDL.Text,
    'studentAdmissionNumber' : IDL.Text,
    'className' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalEmployees' : IDL.Nat,
    'monthlyFeesCollected' : IDL.Nat,
    'totalStudents' : IDL.Nat,
    'pendingDues' : IDL.Nat,
  });
  const PaymentMode = IDL.Variant({
    'cash' : IDL.Null,
    'cheque' : IDL.Null,
    'online' : IDL.Null,
  });
  const FeePayment = IDL.Record({
    'fine' : IDL.Opt(IDL.Nat),
    'studentAdmissionNumber' : IDL.Text,
    'paymentDate' : Time,
    'discount' : IDL.Opt(IDL.Nat),
    'paymentMode' : PaymentMode,
    'amount' : IDL.Nat,
    'receiptNumber' : IDL.Text,
  });
  const StudentMark = IDL.Record({
    'marks' : IDL.Nat,
    'subject' : IDL.Text,
    'studentAdmissionNumber' : IDL.Text,
    'grade' : IDL.Text,
    'examId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClass' : IDL.Func([ClassInfo], [], []),
    'addEmployee' : IDL.Func([Employee], [], []),
    'addExam' : IDL.Func([Exam], [], []),
    'addNotice' : IDL.Func([Notice], [], []),
    'addStudent' : IDL.Func([Student], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteClass' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [], []),
    'deleteExam' : IDL.Func([IDL.Text], [], []),
    'deleteNotice' : IDL.Func([IDL.Text], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'findAdminEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'findEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
    'findStudentByAdminNo' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Student)],
        ['query'],
      ),
    'findSupportStaffEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'findTeacherEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllClasses' : IDL.Func([], [IDL.Vec(ClassInfo)], ['query']),
    'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getAttendance' : IDL.Func(
        [Time, IDL.Text, IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClass' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(ClassInfo)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getExam' : IDL.Func([IDL.Text], [IDL.Opt(Exam)], ['query']),
    'getFeeLedger' : IDL.Func([IDL.Text], [IDL.Vec(FeePayment)], ['query']),
    'getFeePayment' : IDL.Func([IDL.Text], [IDL.Opt(FeePayment)], ['query']),
    'getNotice' : IDL.Func([IDL.Text], [IDL.Opt(Notice)], ['query']),
    'getOutstandingBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getReportCard' : IDL.Func([IDL.Text], [IDL.Vec(StudentMark)], ['query']),
    'getStudentAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getStudentMarks' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(StudentMark)],
        ['query'],
      ),
    'getStudentsByClass' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([Attendance], [], []),
    'recordFeePayment' : IDL.Func([FeePayment], [], []),
    'recordMarks' : IDL.Func([StudentMark], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchStudentsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'updateClass' : IDL.Func([IDL.Text, IDL.Text, ClassInfo], [], []),
    'updateEmployee' : IDL.Func([IDL.Text, Employee], [], []),
    'updateExam' : IDL.Func([IDL.Text, Exam], [], []),
    'updateNotice' : IDL.Func([IDL.Text, Notice], [], []),
    'updateStudent' : IDL.Func([IDL.Text, Student], [], []),
  });
};

export const init = ({ IDL }) => { return []; };