/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'present' : boolean,
  'date' : Time,
  'section' : string,
  'studentAdmissionNumber' : string,
  'className' : string,
}
export interface ClassInfo {
  'subjects' : Array<string>,
  'section' : string,
  'feeStructure' : FeeStructure,
  'className' : string,
}
export interface DashboardStats {
  'totalEmployees' : bigint,
  'monthlyFeesCollected' : bigint,
  'totalStudents' : bigint,
  'pendingDues' : bigint,
}
export interface Employee {
  'active' : boolean,
  'salary' : bigint,
  'name' : string,
  'designation' : string,
  'role' : EmployeeRole,
  'empId' : string,
  'department' : string,
}
export type EmployeeRole = { 'admin' : null } |
  { 'teacher' : null } |
  { 'supportStaff' : null };
export interface Exam {
  'date' : Time,
  'name' : string,
  'section' : string,
  'examId' : string,
  'className' : string,
}
export type ExternalBlob = Uint8Array;
export interface FeePayment {
  'fine' : [] | [bigint],
  'studentAdmissionNumber' : string,
  'paymentDate' : Time,
  'discount' : [] | [bigint],
  'paymentMode' : PaymentMode,
  'amount' : bigint,
  'receiptNumber' : string,
}
export interface FeeStructure {
  'transport' : bigint,
  'tuition' : bigint,
  'examFees' : bigint,
}
export interface Notice {
  'title' : string,
  'postedBy' : string,
  'content' : string,
  'postedDate' : Time,
  'noticeId' : string,
  'attachment' : [] | [ExternalBlob],
}
export type PaymentMode = { 'cash' : null } |
  { 'cheque' : null } |
  { 'online' : null };
export interface Student {
  'contact' : string,
  'admissionDate' : Time,
  'name' : string,
  'section' : string,
  'admissionNumber' : string,
  'photo' : ExternalBlob,
  'className' : string,
  'parentName' : string,
}
export interface StudentMark {
  'marks' : bigint,
  'subject' : string,
  'studentAdmissionNumber' : string,
  'grade' : string,
  'examId' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClass' : ActorMethod<[ClassInfo], undefined>,
  'addEmployee' : ActorMethod<[Employee], undefined>,
  'addExam' : ActorMethod<[Exam], undefined>,
  'addNotice' : ActorMethod<[Notice], undefined>,
  'addStudent' : ActorMethod<[Student], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteClass' : ActorMethod<[string, string], undefined>,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'deleteExam' : ActorMethod<[string], undefined>,
  'deleteNotice' : ActorMethod<[string], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'findAdminEmployees' : ActorMethod<[], Array<Employee>>,
  'findEmployee' : ActorMethod<[string], [] | [Employee]>,
  'findStudentByAdminNo' : ActorMethod<[string], [] | [Student]>,
  'findSupportStaffEmployees' : ActorMethod<[], Array<Employee>>,
  'findTeacherEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllClasses' : ActorMethod<[], Array<ClassInfo>>,
  'getAllNotices' : ActorMethod<[], Array<Notice>>,
  'getAttendance' : ActorMethod<[Time, string, string], Array<Attendance>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClass' : ActorMethod<[string, string], [] | [ClassInfo]>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getExam' : ActorMethod<[string], [] | [Exam]>,
  'getFeeLedger' : ActorMethod<[string], Array<FeePayment>>,
  'getFeePayment' : ActorMethod<[string], [] | [FeePayment]>,
  'getNotice' : ActorMethod<[string], [] | [Notice]>,
  'getOutstandingBalance' : ActorMethod<[string], bigint>,
  'getReportCard' : ActorMethod<[string], Array<StudentMark>>,
  'getStudentAttendance' : ActorMethod<[string], Array<Attendance>>,
  'getStudentMarks' : ActorMethod<[string, string], Array<StudentMark>>,
  'getStudentsByClass' : ActorMethod<[string, string], Array<Student>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[Attendance], undefined>,
  'recordFeePayment' : ActorMethod<[FeePayment], undefined>,
  'recordMarks' : ActorMethod<[StudentMark], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchStudentsByName' : ActorMethod<[string], Array<Student>>,
  'updateClass' : ActorMethod<[string, string, ClassInfo], undefined>,
  'updateEmployee' : ActorMethod<[string, Employee], undefined>,
  'updateExam' : ActorMethod<[string, Exam], undefined>,
  'updateNotice' : ActorMethod<[string, Notice], undefined>,
  'updateStudent' : ActorMethod<[string, Student], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];