/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface Attendance {
    present: boolean;
    date: Time;
    section: string;
    studentAdmissionNumber: string;
    className: string;
}
export interface StudentMark {
    marks: bigint;
    subject: string;
    studentAdmissionNumber: string;
    grade: string;
    examId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FeePayment {
    fine?: bigint;
    studentAdmissionNumber: string;
    paymentDate: Time;
    discount?: bigint;
    paymentMode: PaymentMode;
    amount: bigint;
    receiptNumber: string;
}
export interface DashboardStats {
    totalEmployees: bigint;
    monthlyFeesCollected: bigint;
    totalStudents: bigint;
    pendingDues: bigint;
}
export interface ClassInfo {
    subjects: Array<string>;
    section: string;
    feeStructure: FeeStructure;
    className: string;
}
export interface FeeStructure {
    transport: bigint;
    tuition: bigint;
    examFees: bigint;
}
export interface Exam {
    date: Time;
    name: string;
    section: string;
    examId: string;
    className: string;
}
export interface Notice {
    title: string;
    postedBy: string;
    content: string;
    postedDate: Time;
    noticeId: string;
    attachment?: ExternalBlob;
}
export interface Employee {
    active: boolean;
    salary: bigint;
    name: string;
    designation: string;
    role: EmployeeRole;
    empId: string;
    department: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface Student {
    contact: string;
    admissionDate: Time;
    name: string;
    section: string;
    admissionNumber: string;
    photo: ExternalBlob;
    className: string;
    parentName: string;
}
export enum EmployeeRole {
    admin = "admin",
    teacher = "teacher",
    supportStaff = "supportStaff"
}
export enum PaymentMode {
    cash = "cash",
    cheque = "cheque",
    online = "online"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addClass(classInfo: ClassInfo): Promise<void>;
    addEmployee(employee: Employee): Promise<void>;
    addExam(exam: Exam): Promise<void>;
    addNotice(notice: Notice): Promise<void>;
    addStudent(student: Student): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteClass(className: string, section: string): Promise<void>;
    deleteEmployee(empId: string): Promise<void>;
    deleteExam(examId: string): Promise<void>;
    deleteNotice(noticeId: string): Promise<void>;
    deleteStudent(admissionNumber: string): Promise<void>;
    findAdminEmployees(): Promise<Array<Employee>>;
    findEmployee(empID: string): Promise<Employee | null>;
    findStudentByAdminNo(admissionNumber: string): Promise<Student | null>;
    findSupportStaffEmployees(): Promise<Array<Employee>>;
    findTeacherEmployees(): Promise<Array<Employee>>;
    getAllClasses(): Promise<Array<ClassInfo>>;
    getAllNotices(): Promise<Array<Notice>>;
    getAttendance(date: Time, className: string, section: string): Promise<Array<Attendance>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClass(className: string, section: string): Promise<ClassInfo | null>;
    getDashboardStats(): Promise<DashboardStats>;
    getExam(examId: string): Promise<Exam | null>;
    getFeeLedger(studentAdmissionNumber: string): Promise<Array<FeePayment>>;
    getFeePayment(receiptNumber: string): Promise<FeePayment | null>;
    getNotice(noticeId: string): Promise<Notice | null>;
    getOutstandingBalance(studentAdmissionNumber: string): Promise<bigint>;
    getReportCard(studentAdmissionNumber: string): Promise<Array<StudentMark>>;
    getStudentAttendance(studentAdmissionNumber: string): Promise<Array<Attendance>>;
    getStudentMarks(studentAdmissionNumber: string, examId: string): Promise<Array<StudentMark>>;
    getStudentsByClass(className: string, section: string): Promise<Array<Student>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAttendance(attendanceRecord: Attendance): Promise<void>;
    recordFeePayment(payment: FeePayment): Promise<void>;
    recordMarks(mark: StudentMark): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchStudentsByName(name: string): Promise<Array<Student>>;
    updateClass(className: string, section: string, classInfo: ClassInfo): Promise<void>;
    updateEmployee(empId: string, employee: Employee): Promise<void>;
    updateExam(examId: string, exam: Exam): Promise<void>;
    updateNotice(noticeId: string, notice: Notice): Promise<void>;
    updateStudent(admissionNumber: string, student: Student): Promise<void>;
}
import type { ClassInfo as _ClassInfo, Employee as _Employee, EmployeeRole as _EmployeeRole, Exam as _Exam, ExternalBlob as _ExternalBlob, FeePayment as _FeePayment, Notice as _Notice, PaymentMode as _PaymentMode, Student as _Student, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addClass(arg0: ClassInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClass(arg0);
            return result;
        }
    }
    async addEmployee(arg0: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(to_candid_Employee_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(to_candid_Employee_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addExam(arg0: Exam): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExam(arg0);
            return result;
        }
    }
    async addNotice(arg0: Notice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotice(await to_candid_Notice_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotice(await to_candid_Notice_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addStudent(arg0: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(await to_candid_Student_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(await to_candid_Student_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteClass(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClass(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClass(arg0, arg1);
            return result;
        }
    }
    async deleteEmployee(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async deleteExam(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExam(arg0);
            return result;
        }
    }
    async deleteNotice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async findAdminEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.findAdminEmployees();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findAdminEmployees();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async findEmployee(arg0: string): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findEmployee(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findEmployee(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async findStudentByAdminNo(arg0: string): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findStudentByAdminNo(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findStudentByAdminNo(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async findSupportStaffEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.findSupportStaffEmployees();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findSupportStaffEmployees();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async findTeacherEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.findTeacherEmployees();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findTeacherEmployees();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClasses(): Promise<Array<ClassInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClasses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClasses();
            return result;
        }
    }
    async getAllNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotices();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotices();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendance(arg0: Time, arg1: string, arg2: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendance(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendance(arg0, arg1, arg2);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClass(arg0: string, arg1: string): Promise<ClassInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClass(arg0, arg1);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClass(arg0, arg1);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getExam(arg0: string): Promise<Exam | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExam(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExam(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeeLedger(arg0: string): Promise<Array<FeePayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeLedger(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeLedger(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeePayment(arg0: string): Promise<FeePayment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeePayment(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeePayment(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotice(arg0: string): Promise<Notice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotice(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotice(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOutstandingBalance(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutstandingBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutstandingBalance(arg0);
            return result;
        }
    }
    async getReportCard(arg0: string): Promise<Array<StudentMark>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportCard(arg0);
            return result;
        }
    }
    async getStudentAttendance(arg0: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentAttendance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentAttendance(arg0);
            return result;
        }
    }
    async getStudentMarks(arg0: string, arg1: string): Promise<Array<StudentMark>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentMarks(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentMarks(arg0, arg1);
            return result;
        }
    }
    async getStudentsByClass(arg0: string, arg1: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByClass(arg0, arg1);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsByClass(arg0, arg1);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAttendance(arg0: Attendance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0);
            return result;
        }
    }
    async recordFeePayment(arg0: FeePayment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordFeePayment(to_candid_FeePayment_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordFeePayment(to_candid_FeePayment_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async recordMarks(arg0: StudentMark): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordMarks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordMarks(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchStudentsByName(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudentsByName(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudentsByName(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClass(arg0: string, arg1: string, arg2: ClassInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClass(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClass(arg0, arg1, arg2);
            return result;
        }
    }
    async updateEmployee(arg0: string, arg1: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, to_candid_Employee_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, to_candid_Employee_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateExam(arg0: string, arg1: Exam): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExam(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExam(arg0, arg1);
            return result;
        }
    }
    async updateNotice(arg0: string, arg1: Notice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotice(arg0, await to_candid_Notice_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotice(arg0, await to_candid_Notice_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStudent(arg0: string, arg1: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, await to_candid_Student_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, await to_candid_Student_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_EmployeeRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeRole): EmployeeRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Employee_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FeePayment_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeePayment): FeePayment {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_Notice_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notice): Promise<Notice> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMode_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_Student_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Promise<Student> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Employee | null {
    return value.length === 0 ? null : from_candid_Employee_n20(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Promise<Student | null> {
    return value.length === 0 ? null : await from_candid_Student_n26(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClassInfo]): ClassInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Exam]): Exam | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FeePayment]): FeePayment | null {
    return value.length === 0 ? null : from_candid_FeePayment_n39(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Notice]): Promise<Notice | null> {
    return value.length === 0 ? null : await from_candid_Notice_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    salary: bigint;
    name: string;
    designation: string;
    role: _EmployeeRole;
    empId: string;
    department: string;
}): {
    active: boolean;
    salary: bigint;
    name: string;
    designation: string;
    role: EmployeeRole;
    empId: string;
    department: string;
} {
    return {
        active: value.active,
        salary: value.salary,
        name: value.name,
        designation: value.designation,
        role: from_candid_EmployeeRole_n22(_uploadFile, _downloadFile, value.role),
        empId: value.empId,
        department: value.department
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: string;
    admissionDate: _Time;
    name: string;
    section: string;
    admissionNumber: string;
    photo: _ExternalBlob;
    className: string;
    parentName: string;
}): Promise<{
    contact: string;
    admissionDate: Time;
    name: string;
    section: string;
    admissionNumber: string;
    photo: ExternalBlob;
    className: string;
    parentName: string;
}> {
    return {
        contact: value.contact,
        admissionDate: value.admissionDate,
        name: value.name,
        section: value.section,
        admissionNumber: value.admissionNumber,
        photo: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.photo),
        className: value.className,
        parentName: value.parentName
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    postedBy: string;
    content: string;
    postedDate: _Time;
    noticeId: string;
    attachment: [] | [_ExternalBlob];
}): Promise<{
    title: string;
    postedBy: string;
    content: string;
    postedDate: Time;
    noticeId: string;
    attachment?: ExternalBlob;
}> {
    return {
        title: value.title,
        postedBy: value.postedBy,
        content: value.content,
        postedDate: value.postedDate,
        noticeId: value.noticeId,
        attachment: record_opt_to_undefined(await from_candid_opt_n32(_uploadFile, _downloadFile, value.attachment))
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fine: [] | [bigint];
    studentAdmissionNumber: string;
    paymentDate: _Time;
    discount: [] | [bigint];
    paymentMode: _PaymentMode;
    amount: bigint;
    receiptNumber: string;
}): {
    fine?: bigint;
    studentAdmissionNumber: string;
    paymentDate: Time;
    discount?: bigint;
    paymentMode: PaymentMode;
    amount: bigint;
    receiptNumber: string;
} {
    return {
        fine: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.fine)),
        studentAdmissionNumber: value.studentAdmissionNumber,
        paymentDate: value.paymentDate,
        discount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.discount)),
        paymentMode: from_candid_PaymentMode_n41(_uploadFile, _downloadFile, value.paymentMode),
        amount: value.amount,
        receiptNumber: value.receiptNumber
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    teacher: null;
} | {
    supportStaff: null;
}): EmployeeRole {
    return "admin" in value ? EmployeeRole.admin : "teacher" in value ? EmployeeRole.teacher : "supportStaff" in value ? EmployeeRole.supportStaff : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    cheque: null;
} | {
    online: null;
}): PaymentMode {
    return "cash" in value ? PaymentMode.cash : "cheque" in value ? PaymentMode.cheque : "online" in value ? PaymentMode.online : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n20(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notice>): Promise<Array<Notice>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Notice_n30(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeePayment>): Array<FeePayment> {
    return value.map((x)=>from_candid_FeePayment_n39(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Promise<Array<Student>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Student_n26(_uploadFile, _downloadFile, x)));
}
function to_candid_EmployeeRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): _EmployeeRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Employee_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): _Employee {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FeePayment_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeePayment): _FeePayment {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_Notice_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Notice): Promise<_Notice> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMode_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
async function to_candid_Student_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Student): Promise<_Student> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    postedBy: string;
    content: string;
    postedDate: Time;
    noticeId: string;
    attachment?: ExternalBlob;
}): Promise<{
    title: string;
    postedBy: string;
    content: string;
    postedDate: _Time;
    noticeId: string;
    attachment: [] | [_ExternalBlob];
}> {
    return {
        title: value.title,
        postedBy: value.postedBy,
        content: value.content,
        postedDate: value.postedDate,
        noticeId: value.noticeId,
        attachment: value.attachment ? candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.attachment)) : candid_none()
    };
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: string;
    admissionDate: Time;
    name: string;
    section: string;
    admissionNumber: string;
    photo: ExternalBlob;
    className: string;
    parentName: string;
}): Promise<{
    contact: string;
    admissionDate: _Time;
    name: string;
    section: string;
    admissionNumber: string;
    photo: _ExternalBlob;
    className: string;
    parentName: string;
}> {
    return {
        contact: value.contact,
        admissionDate: value.admissionDate,
        name: value.name,
        section: value.section,
        admissionNumber: value.admissionNumber,
        photo: await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.photo),
        className: value.className,
        parentName: value.parentName
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fine?: bigint;
    studentAdmissionNumber: string;
    paymentDate: Time;
    discount?: bigint;
    paymentMode: PaymentMode;
    amount: bigint;
    receiptNumber: string;
}): {
    fine: [] | [bigint];
    studentAdmissionNumber: string;
    paymentDate: _Time;
    discount: [] | [bigint];
    paymentMode: _PaymentMode;
    amount: bigint;
    receiptNumber: string;
} {
    return {
        fine: value.fine ? candid_some(value.fine) : candid_none(),
        studentAdmissionNumber: value.studentAdmissionNumber,
        paymentDate: value.paymentDate,
        discount: value.discount ? candid_some(value.discount) : candid_none(),
        paymentMode: to_candid_PaymentMode_n48(_uploadFile, _downloadFile, value.paymentMode),
        amount: value.amount,
        receiptNumber: value.receiptNumber
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    salary: bigint;
    name: string;
    designation: string;
    role: EmployeeRole;
    empId: string;
    department: string;
}): {
    active: boolean;
    salary: bigint;
    name: string;
    designation: string;
    role: _EmployeeRole;
    empId: string;
    department: string;
} {
    return {
        active: value.active,
        salary: value.salary,
        name: value.name,
        designation: value.designation,
        role: to_candid_EmployeeRole_n10(_uploadFile, _downloadFile, value.role),
        empId: value.empId,
        department: value.department
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): {
    admin: null;
} | {
    teacher: null;
} | {
    supportStaff: null;
} {
    return value == EmployeeRole.admin ? {
        admin: null
    } : value == EmployeeRole.teacher ? {
        teacher: null
    } : value == EmployeeRole.supportStaff ? {
        supportStaff: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    cash: null;
} | {
    cheque: null;
} | {
    online: null;
} {
    return value == PaymentMode.cash ? {
        cash: null
    } : value == PaymentMode.cheque ? {
        cheque: null
    } : value == PaymentMode.online ? {
        online: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
